---
title: '#rmdnews updates 2019-03-06'
author: Martin John Hadley
date: '2019-03-06'
slug: rmdnews-updates-2019-03-06
categories:
  - R
tags:
  - rmdnews
---

```{r emoji, include=FALSE}
library("emo")
```


It's hard keeping up to date with the awesome new things that we can do with #rstats. There are new packages and interesting new use cases of existing `r emo::ji("package")` coming out all of the time. Mara Averick ([@dataandme](https://twitter.com/dataandme)) is an incredible source of overviews and introductions to awesome stuff, if you don't already follow her then do so immediately.

But how about `r emo::ji("package")` updates? We often upgrade a package in a rush when we're told the `r emo::ji("package")` we want to install requires a new version of X. This means we miss out on potentially useful (or exciting) new features of packages that we already know and love.

So, I suggest as a community we use #rmdnews to tag tweets and blogposts that are solely to do with updates to existing packages. Why this hashtag? Most [^1] R packages contain a [NEWS.md file](http://r-pkgs.had.co.nz/release.html#news) which is where package developers are encouraged to document updates and new features in their `r emo::ji("package")`. You find the NEWS.md file in one of two places:

- On CRAN in the DESCRIPTION file, e.g. [https://cran.r-project.org/web/packages/dplyr/index.html](https://cran.r-project.org/web/packages/dplyr/index.html)

- If the package is on Github, it's extremely likely [^1] to have a NEWS.md file in the repo, e.g. 


[1]: Citation needed. Or better yet, data.
