---
title: 'Static maps: ggplot2 vs ggmap vs tmap'
author: ''
date: '2019-02-19'
slug: static-maps-ggplot2-vs-ggmap-vs-tmap
categories: []
tags: []
editor_options: 
  chunk_output_type: console
---

```{r, eval = FALSE}
library(tmap)
library(tmaptools)

read_osm()
```


I'm incredibly happy to be corrected on this, but it seems in 2019 there are three options for creating static maps in R:

- ggplot2: We can create geo-m

| ggplot2 | ggmap | tmap |
| :--: | :--: | :--: |
| dd | ddd | ddd |


| - one
- two | three | four

```{r, eval = FALSE}
library(leaflet)
library(leaflet.extras)
leaflet() %>%
  addTiles() %>%
  addControlGPS()
```


```{r, eval = FALSE}
library("sf")
library("tidyverse")

quakes_sf <- quakes %>%
  st_as_sf(coords = c("long", "lat"))


quakes_sf
sf::st_as_sfc(quakes_sf, "data.frame")

quakes_tib <- quakes_sf
st_geometry(quakes_tib) <- NULL

quakes_sf %>%
  st_set_crs(4326) %>%
  st_transform("+init=epsg:4326")

nc = st_read(system.file("shape/nc.shp", package="sf"))
st_combine(nc)

nc %>%
  st_proj_info()

nc %>%
  head() %>%
  mutate(new = AREA) %>%
  mutate(new = st_centroid(geometry) %>% st_coordinates())


```






